### ISSUE TITLE
Failed to install 'cordova-plugin-mixpanel' for ios

### ISSUE THREAD

**Issue by shnist** [samzilverberg/cordova-mixpanel-plugin#100]
Getting the following error when trying to install cordova-plugin-mixpanel 4.6.0

```
> cordova plugin add cordova-plugin-mixpanel@latest --save
Installing "cordova-plugin-mixpanel" for ios
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-mixpanel': CordovaError: Uh oh!
Cannot find resource file "/Users/aaron/Sites/lumo-app/packages/lumo-ionic-app/plugins/cordova-plugin-mixpanel/src/ios/Mixpanel/.DS_Store" for plugin cordova-plugin-mixpanel in iOS platform
    at install (/Users/aaron/Sites/lumo-app/packages/lumo-ionic-app/platforms/ios/cordova/lib/plugman/pluginHandlers.js:61:23)
    at ActionStack.process (/Users/aaron/Sites/lumo-app/packages/lumo-ionic-app/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/aaron/Sites/lumo-app/packages/lumo-ionic-app/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/Users/aaron/Sites/lumo-app/packages/lumo-ionic-app/node_modules/cordova-common/src/PluginManager.js:144:17)
    at Api.addPlugin (/Users/aaron/Sites/lumo-app/packages/lumo-ionic-app/platforms/ios/cordova/Api.js:247:10)
    at handleInstall (/Users/aaron/.nvm/versions/node/v8.12.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:594:10)
    at /Users/aaron/.nvm/versions/node/v8.12.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:357:28
    at _fulfilled (/Users/aaron/.nvm/versions/node/v8.12.0/lib/node_modules/cordova/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/Users/aaron/.nvm/versions/node/v8.12.0/lib/node_modules/cordova/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/Users/aaron/.nvm/versions/node/v8.12.0/lib/node_modules/cordova/node_modules/q/q.js:816:13)
Uh oh!
Cannot find resource file "/Users/aaron/Sites/lumo-app/packages/lumo-ionic-app/plugins/cordova-plugin-mixpanel/src/ios/Mixpanel/.DS_Store" for plugin cordova-plugin-mixpanel in iOS platform
```

cordova info:
```
Node version: v8.12.0

Cordova version: 8.1.1

Config.xml file:

<?xml version='1.0' encoding='utf-8'?>
<widget android-versionCode="11940008" id="..." ios-CFBundleIdentifier="..." ios-CFBundleShortVersionString="1.0.8" ios-CFBundleVersion="1194000" version="1.0.1940" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>...</name>
    <description>...</description>
    <author email="..." href="http://ionicframework.com/">...</author>
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" launch-external="yes" />
    <allow-intent href="https://*/*" launch-external="yes" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
        <allow-navigation href="*" />
        <resource-file src="resources/android/google-services.json" target="app/google-services.json" />
        <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
        <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />
        <icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png" />
        <icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.png" />
        <icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.png" />
        <icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-icon.png" />
        <splash density="land-ldpi" src="resources/android/splash/drawable-land-ldpi-screen.png" />
        <splash density="land-mdpi" src="resources/android/splash/drawable-land-mdpi-screen.png" />
        <splash density="land-hdpi" src="resources/android/splash/drawable-land-hdpi-screen.png" />
        <splash density="land-xhdpi" src="resources/android/splash/drawable-land-xhdpi-screen.png" />
        <splash density="land-xxhdpi" src="resources/android/splash/drawable-land-xxhdpi-screen.png" />
        <splash density="land-xxxhdpi" src="resources/android/splash/drawable-land-xxxhdpi-screen.png" />
        <splash density="port-ldpi" src="resources/android/splash/drawable-port-ldpi-screen.png" />
        <splash density="port-mdpi" src="resources/android/splash/drawable-port-mdpi-screen.png" />
        <splash density="port-hdpi" src="resources/android/splash/drawable-port-hdpi-screen.png" />
        <splash density="port-xhdpi" src="resources/android/splash/drawable-port-xhdpi-screen.png" />
        <splash density="port-xxhdpi" src="resources/android/splash/drawable-port-xxhdpi-screen.png" />
        <splash density="port-xxxhdpi" src="resources/android/splash/drawable-port-xxxhdpi-screen.png" />
    </platform>
    <platform name="ios">
        <allow-navigation href="*" />
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <icon height="57" src="resources/ios/icon/icon.png" width="57" />
        <icon height="114" src="resources/ios/icon/icon@2x.png" width="114" />
        <icon height="40" src="resources/ios/icon/icon-40.png" width="40" />
        <icon height="80" src="resources/ios/icon/icon-40@2x.png" width="80" />
        <icon height="120" src="resources/ios/icon/icon-40@3x.png" width="120" />
        <icon height="50" src="resources/ios/icon/icon-50.png" width="50" />
        <icon height="100" src="resources/ios/icon/icon-50@2x.png" width="100" />
        <icon height="60" src="resources/ios/icon/icon-60.png" width="60" />
        <icon height="120" src="resources/ios/icon/icon-60@2x.png" width="120" />
        <icon height="180" src="resources/ios/icon/icon-60@3x.png" width="180" />
        <icon height="72" src="resources/ios/icon/icon-72.png" width="72" />
        <icon height="144" src="resources/ios/icon/icon-72@2x.png" width="144" />
        <icon height="76" src="resources/ios/icon/icon-76.png" width="76" />
        <icon height="152" src="resources/ios/icon/icon-76@2x.png" width="152" />
        <icon height="167" src="resources/ios/icon/icon-83.5@2x.png" width="167" />
        <icon height="29" src="resources/ios/icon/icon-small.png" width="29" />
        <icon height="58" src="resources/ios/icon/icon-small@2x.png" width="58" />
        <icon height="87" src="resources/ios/icon/icon-small@3x.png" width="87" />
        <icon height="1024" src="resources/ios/icon/icon-1024.png" width="1024" />
        <splash height="1136" src="resources/ios/splash/Default-568h@2x~iphone.png" width="640" />
        <splash height="1334" src="resources/ios/splash/Default-667h.png" width="750" />
        <splash height="2208" src="resources/ios/splash/Default-736h.png" width="1242" />
        <splash height="1242" src="resources/ios/splash/Default-Landscape-736h.png" width="2208" />
        <splash height="1536" src="resources/ios/splash/Default-Landscape@2x~ipad.png" width="2048" />
        <splash height="2048" src="resources/ios/splash/Default-Landscape@~ipadpro.png" width="2732" />
        <splash height="768" src="resources/ios/splash/Default-Landscape~ipad.png" width="1024" />
        <splash height="2048" src="resources/ios/splash/Default-Portrait@2x~ipad.png" width="1536" />
        <splash height="2732" src="resources/ios/splash/Default-Portrait@~ipadpro.png" width="2048" />
        <splash height="1024" src="resources/ios/splash/Default-Portrait~ipad.png" width="768" />
        <splash height="960" src="resources/ios/splash/Default@2x~iphone.png" width="640" />
        <splash height="480" src="resources/ios/splash/Default~iphone.png" width="320" />
        <splash height="2732" src="resources/ios/splash/Default@2x~universal~anyany.png" width="2732" />
    </platform>
    <feature name="CDVWKWebViewEngine">
        <param name="ios-package" value="CDVWKWebViewEngine" />
    </feature>
    <feature name="StatusBar">
        <param name="ios-package" onload="true" value="CDVStatusBar" />
    </feature>
    <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
    <preference name="webviewbounce" value="false" />
    <preference name="UIWebViewBounce" value="false" />
    <preference name="DisallowOverscroll" value="true" />
    <preference name="android-minSdkVersion" value="19" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="FadeSplashScreenDuration" value="2000" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="ShowSplashScreenSpinner" value="false" />
    <preference name="AutoHideSplashScreen" value="false" />
    <preference name="KeyboardDisplayRequiresUserAction" value="false" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="3000" />
    <preference name="orientation" value="portrait" />
    <preference name="target-device" value="handset" />
    <preference name="intercom-app-id" value="klqx8zcy" />
    <preference name="intercom-ios-api-key" value="ios_sdk-6500c98263feb18f4e96ea7645f378d4374959b3" />
    <preference name="intercom-android-api-key" value="android_sdk-1453c63f70e7c70e3a6f68f2ff33b605b68fc999" />
    <plugin name="cordova-android-support-gradle-release" spec="^1.3.0">
        <variable name="ANDROID_SUPPORT_VERSION" value="27.+" />
    </plugin>
    <plugin name="cordova-open-native-settings" spec="^1.5.1" />
    <plugin name="cordova-plugin-add-swift-support" spec="^1.7.2" />
    <plugin name="cordova-plugin-app-version" spec="^0.1.9" />
    <plugin name="cordova-plugin-calendar" spec="^5.0.0">
        <variable name="CALENDAR_USAGE_DESCRIPTION" value="To add smart meter booking to calendar" />
    </plugin>
    <plugin name="cordova-plugin-device" spec="^2.0.2" />
    <plugin name="cordova-plugin-email-composer" spec="^0.8.15" />
    <plugin name="cordova-plugin-file" spec="^6.0.1" />
    <plugin name="cordova-plugin-file-transfer" spec="^1.7.1" />
    <plugin name="cordova-plugin-network-information" spec="^2.0.1" />
    <plugin name="cordova-plugin-no-export-compliance-ios" spec="0.0.2" />
    <plugin name="cordova-plugin-splashscreen" spec="^5.0.2" />
    <plugin name="cordova-plugin-statusbar" spec="^2.4.2" />
    <plugin name="cordova-plugin-themeablebrowser" spec="github:Manny91/cordova-plugin-themeablebrowser" />
    <plugin name="cordova-plugin-whitelist" spec="^1.3.3" />
    <plugin name="ionic-plugin-keyboard" spec="^2.2.1" />
    <plugin name="ionic-plugin-deeplinks" spec="~1.0.17">
        <variable name="URL_SCHEME" value="lumoapp" />
        <variable name="DEEPLINK_SCHEME" value="https" />
        <variable name="DEEPLINK_HOST" value="lumoapp.co.uk" />
    </plugin>
    <plugin name="phonegap-plugin-barcodescanner" spec="^8.0.0">
        <variable name="ANDROID_SUPPORT_V4_VERSION" value="27.+" />
    </plugin>
    <plugin name="phonegap-plugin-push" spec="^2.2.3">
        <variable name="SENDER_ID" value="85075801930" />
        <variable name="ANDROID_SUPPORT_V13_VERSION" value="27.+" />
        <variable name="FCM_VERSION" value="11.0.1" />
    </plugin>
    <plugin name="cordova-plugin-file-opener2" spec="2.1.0">
        <variable name="ANDROID_SUPPORT_V4_VERSION" value="27.+" />
    </plugin>
    <plugin name="cordova-plugin-ionic-webview" spec="2.3.1">
        <variable name="ANDROID_SUPPORT_ANNOTATIONS_VERSION" value="27.+" />
    </plugin>
    <plugin name="cordova-sqlite-storage" spec="2.6.0" />
    <plugin name="cordova-plugin-intercom" spec="^6.2.0" />
    <edit-config file="*-Info.plist" mode="merge" target="NSCameraUsageDescription">
        <string>To scan QR codes on utility bills</string>
    </edit-config>
    <engine name="browser" spec="^5.0.4" />
    <engine name="ios" spec="~5.0.0" />
    <engine name="android" spec="~7.1.2" />
</widget>

iOS platform:

Xcode 10.2
Build version 10E125
```

Installing `4.5.2` is fine.

**Comment by samzilverberg** [comment]
yup, i accidently put `.DS_STORE` in plugin.xml with my last version
https://github.com/samzilverberg/cordova-mixpanel-plugin/blob/master/plugin.xml#L237

pinning the version to 4.5.2 works.
i will re-release with the fix (probably later this week)

**Comment by samzilverberg** [comment]
just re-released with possible fix (removing ref to ds_store), give it a try
