### ISSUE TITLE
FirebaseApp not initialized Android on Mixpanel.init()

### ISSUE THREAD

**Issue by bartboersma** [samzilverberg/cordova-mixpanel-plugin#116]
Hi,

When calling Mixpanel.init() on android I am receiving the following error:
E/PluginManager: Uncaught exception from plugin
`E/PluginManager: Uncaught exception from plugin
    java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process *.*.*. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(com.google.firebase:firebase-common@@17.0.0:234)
        at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source:1)
        at com.mixpanel.android.mpmetrics.MixpanelFCMMessagingService.init(MixpanelFCMMessagingService.java:117)
        at com.mixpanel.android.mpmetrics.MixpanelAPI.getInstance(MixpanelAPI.java:423)
        at com.mixpanel.android.mpmetrics.MixpanelAPI.getInstance(MixpanelAPI.java:369)
        at com.samz.cordova.mixpanel.MixpanelPlugin.handleInit(MixpanelPlugin.java:207)
        at com.samz.cordova.mixpanel.MixpanelPlugin.execute(MixpanelPlugin.java:103)`

I've noticed that if I call init twice then the second one works. Thus it seems that during the first init, eventhough it throws the error it somehow initializes the FirebaseApp. 

I do see at the start up the following line being logged:
`Default FirebaseApp failed to initialize because no default options were found. This usually means that com.google.gms:google-services was not applied to your gradle project.`

Do you have a clue how to resolve this?

Cheers!

**Comment by bartboersma** [comment]
I solved this by adding a google-services.json file to my Ionic project in the android/app folder. I was not aware of what Firebase was and nowhere I read that a google-services.json was needed. Is this something obvious that I missed or is it such common knowledge that its expected to be known that if you use mixpanel you need Firebase hense you need google-services.json?

Cheers
