### ISSUE TITLE
Plugin cannot be installed

### ISSUE THREAD

**Issue by degaray** [samzilverberg/cordova-mixpanel-plugin#66]
I get this error when trying to install.

`cordova plugin add cordova-plugin-mixpanel
`

Installing "cordova-plugin-mixpanel" for android
Subproject Path: CordovaLib
Installing "cordova-plugin-mixpanel" for ios
Failed to install 'cordova-plugin-mixpanel': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/my project/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by samzilverberg** [comment]
Do you have cocoapod installed? Check readme if you don't know what it is

**Comment by degaray** [comment]
Yes that was the problem. Thank you very much!
